theme: jekyll-theme-midnight
title: "MANIAC MUSIC"
description: "Everything music: Concert dates, artists, songs, lyrics, and more!"
gitorg: "https://github.com/avac54765/ManiacMusic"
google_analytics:
